/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MetalsRouteImport } from './routes/metals'
import { Route as MemesRouteImport } from './routes/memes'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CurrencyRouteImport } from './routes/currency'
import { Route as CommoditiesRouteImport } from './routes/commodities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTrafficRouteImport } from './routes/admin/traffic'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminParsingRouteImport } from './routes/admin/parsing'
import { Route as AdminCurrenciesRouteImport } from './routes/admin/currencies'
import { Route as AdminCommoditiesLogsRouteImport } from './routes/admin/commodities-logs'
import { Route as AdminCommoditiesRouteImport } from './routes/admin/commodities'
import { Route as AdminBansRouteImport } from './routes/admin/bans'

const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MetalsRoute = MetalsRouteImport.update({
  id: '/metals',
  path: '/metals',
  getParentRoute: () => rootRouteImport,
} as any)
const MemesRoute = MemesRouteImport.update({
  id: '/memes',
  path: '/memes',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyRoute = CurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const CommoditiesRoute = CommoditiesRouteImport.update({
  id: '/commodities',
  path: '/commodities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrafficRoute = AdminTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParsingRoute = AdminParsingRouteImport.update({
  id: '/parsing',
  path: '/parsing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurrenciesRoute = AdminCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommoditiesLogsRoute = AdminCommoditiesLogsRouteImport.update({
  id: '/commodities-logs',
  path: '/commodities-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommoditiesRoute = AdminCommoditiesRouteImport.update({
  id: '/commodities',
  path: '/commodities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBansRoute = AdminBansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/commodities': typeof CommoditiesRoute
  '/currency': typeof CurrencyRoute
  '/docs': typeof DocsRoute
  '/facts': typeof FactsRoute
  '/holidays': typeof HolidaysRoute
  '/memes': typeof MemesRoute
  '/metals': typeof MetalsRoute
  '/movies': typeof MoviesRoute
  '/admin/bans': typeof AdminBansRoute
  '/admin/commodities': typeof AdminCommoditiesRoute
  '/admin/commodities-logs': typeof AdminCommoditiesLogsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/parsing': typeof AdminParsingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/traffic': typeof AdminTrafficRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commodities': typeof CommoditiesRoute
  '/currency': typeof CurrencyRoute
  '/docs': typeof DocsRoute
  '/facts': typeof FactsRoute
  '/holidays': typeof HolidaysRoute
  '/memes': typeof MemesRoute
  '/metals': typeof MetalsRoute
  '/movies': typeof MoviesRoute
  '/admin/bans': typeof AdminBansRoute
  '/admin/commodities': typeof AdminCommoditiesRoute
  '/admin/commodities-logs': typeof AdminCommoditiesLogsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/parsing': typeof AdminParsingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/traffic': typeof AdminTrafficRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/commodities': typeof CommoditiesRoute
  '/currency': typeof CurrencyRoute
  '/docs': typeof DocsRoute
  '/facts': typeof FactsRoute
  '/holidays': typeof HolidaysRoute
  '/memes': typeof MemesRoute
  '/metals': typeof MetalsRoute
  '/movies': typeof MoviesRoute
  '/admin/bans': typeof AdminBansRoute
  '/admin/commodities': typeof AdminCommoditiesRoute
  '/admin/commodities-logs': typeof AdminCommoditiesLogsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/parsing': typeof AdminParsingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/traffic': typeof AdminTrafficRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/commodities'
    | '/currency'
    | '/docs'
    | '/facts'
    | '/holidays'
    | '/memes'
    | '/metals'
    | '/movies'
    | '/admin/bans'
    | '/admin/commodities'
    | '/admin/commodities-logs'
    | '/admin/currencies'
    | '/admin/parsing'
    | '/admin/settings'
    | '/admin/traffic'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commodities'
    | '/currency'
    | '/docs'
    | '/facts'
    | '/holidays'
    | '/memes'
    | '/metals'
    | '/movies'
    | '/admin/bans'
    | '/admin/commodities'
    | '/admin/commodities-logs'
    | '/admin/currencies'
    | '/admin/parsing'
    | '/admin/settings'
    | '/admin/traffic'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/commodities'
    | '/currency'
    | '/docs'
    | '/facts'
    | '/holidays'
    | '/memes'
    | '/metals'
    | '/movies'
    | '/admin/bans'
    | '/admin/commodities'
    | '/admin/commodities-logs'
    | '/admin/currencies'
    | '/admin/parsing'
    | '/admin/settings'
    | '/admin/traffic'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommoditiesRoute: typeof CommoditiesRoute
  CurrencyRoute: typeof CurrencyRoute
  DocsRoute: typeof DocsRoute
  FactsRoute: typeof FactsRoute
  HolidaysRoute: typeof HolidaysRoute
  MemesRoute: typeof MemesRoute
  MetalsRoute: typeof MetalsRoute
  MoviesRoute: typeof MoviesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metals': {
      id: '/metals'
      path: '/metals'
      fullPath: '/metals'
      preLoaderRoute: typeof MetalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memes': {
      id: '/memes'
      path: '/memes'
      fullPath: '/memes'
      preLoaderRoute: typeof MemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commodities': {
      id: '/commodities'
      path: '/commodities'
      fullPath: '/commodities'
      preLoaderRoute: typeof CommoditiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traffic': {
      id: '/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AdminTrafficRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parsing': {
      id: '/admin/parsing'
      path: '/parsing'
      fullPath: '/admin/parsing'
      preLoaderRoute: typeof AdminParsingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/currencies': {
      id: '/admin/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminCurrenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commodities-logs': {
      id: '/admin/commodities-logs'
      path: '/commodities-logs'
      fullPath: '/admin/commodities-logs'
      preLoaderRoute: typeof AdminCommoditiesLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commodities': {
      id: '/admin/commodities'
      path: '/commodities'
      fullPath: '/admin/commodities'
      preLoaderRoute: typeof AdminCommoditiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bans': {
      id: '/admin/bans'
      path: '/bans'
      fullPath: '/admin/bans'
      preLoaderRoute: typeof AdminBansRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBansRoute: typeof AdminBansRoute
  AdminCommoditiesRoute: typeof AdminCommoditiesRoute
  AdminCommoditiesLogsRoute: typeof AdminCommoditiesLogsRoute
  AdminCurrenciesRoute: typeof AdminCurrenciesRoute
  AdminParsingRoute: typeof AdminParsingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrafficRoute: typeof AdminTrafficRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBansRoute: AdminBansRoute,
  AdminCommoditiesRoute: AdminCommoditiesRoute,
  AdminCommoditiesLogsRoute: AdminCommoditiesLogsRoute,
  AdminCurrenciesRoute: AdminCurrenciesRoute,
  AdminParsingRoute: AdminParsingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrafficRoute: AdminTrafficRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommoditiesRoute: CommoditiesRoute,
  CurrencyRoute: CurrencyRoute,
  DocsRoute: DocsRoute,
  FactsRoute: FactsRoute,
  HolidaysRoute: HolidaysRoute,
  MemesRoute: MemesRoute,
  MetalsRoute: MetalsRoute,
  MoviesRoute: MoviesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
